#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-$(CONFIG_RTL8180)		+= rtl818x/
obj-$(CONFIG_RTL8187)		+= rtl818x/
obj-$(CONFIG_RTLWIFI)		+= rtlwifi/
obj-$(CONFIG_RTL8XXXU)		+= rtl8xxxu/
obj-$(CONFIG_RTL8812AU)		+= rtl8812AU_8821AU_linux/
obj-$(CONFIG_RTL8814AU)		+= rtl8814au/
obj-$(CONFIG_RTL8822BE)		+= rtl8822be/
obj-$(CONFIG_RTL8822CE)		+= rtl8822ce/
