ccflags-y += -Wall

ccflags-y += -DILITEK_KERNEL_DRIVER

obj-$(CONFIG_TOUCHSCREEN_ILITEK) += ilitek_ts.o

ilitek_ts-y := \
	ilitek_main.o \
	ilitek_platform_init.o \
	ilitek_update.o \
	ilitek_tool.o \
	ilitek_protocol.o
